package com.taskowolf.audit.domain

enum class AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGED, PROFILE_UPDATED, ROLE_CHANGED,
    API_KEY_CREATED, API_KEY_DELETED, OAUTH_LOGIN, USER_REGISTERED,
    ISSUE_CREATED, ISSUE_UPDATED, ISSUE_DELETED, ISSUE_TRANSITIONED,
    COMMENT_CREATED, COMMENT_DELETED, SPRINT_STARTED, SPRINT_COMPLETED,
    MEMBER_ADDED, MEMBER_REMOVED, WEBHOOK_CREATED, WEBHOOK_DELETED, SLA_BREACHED,
    ISSUE_VIEWED, BOARD_OPENED, REPORT_VIEWED
}
